# -*- coding: utf-8 -*-
"""Pandas_Cleaning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7YxzX_Gn7sopMd-PYj8uMUkdPMlh3vF
"""

import pandas as pd

from datasets import load_dataset

dataset =load_dataset('lukebarousse/data_jobs') #loading data

df =dataset['train'].to_pandas()

df

df.info()

df.job_posted_date

type(df.job_posted_date[0])

pd.to_datetime(df.job_posted_date)

df.info()

df['job_posted_date']=pd.to_datetime(df.job_posted_date) #converts to datetime

df.job_posted_date.dt.month

df['job_posted_month'] = df.job_posted_date.dt.month

df.info()

df

df.sort_values(by ='job_posted_date',inplace =True)

df

df.drop(labels ='salary_hour_avg',axis = 1,inplace = True) # drop column

df.info()

df.dropna(subset =['salary_year_avg'],inplace=True) # drops rows that have na values

df.info()



































